# +-----------------------------------------------------------------------+
# |                         FRESH CORE CONFIGURATION                      |
# |                      Developed by: pandress                           |
# +-----------------------------------------------------------------------+

modules:
  # Configuración de filtrado:
  # show-players: Muestra la barra al apuntar a jugadores.
  # show-mobs: Muestra la barra al apuntar a animales/monstruos.
  mobboard:
    enabled: true
    distance: 6.0
    show-players: true
    show-mobs: true