# +-----------------------------------------------------------------------+
# |                         FRESH CORE CONFIGURATION                      |
# |                      Developed by: pandress                           |
# +-----------------------------------------------------------------------+

modules:
tempfly:
  disabled-worlds:
    - "spawnnuevo"
    - "dungeons"