name: Fresh
version: 1.0
main: cl.pandress.Fresh
api-version: '1.21'
softdepend: [aCore, PlaceholderAPI, Vault]

commands:
  misionesadmin:
    description: Comando administrativo para testear el sistema de misiones.
    permission: fresh.admin
    permission-message: §cNo tienes permiso para usar este comando.
  fresh:
    description: Comando administrativo de Fresh
    permission: fresh.admin
    usage: /fresh reload <module>
  misiones:
    description: Abre el menú de misiones diarias
    aliases: [ quests, m, racha ]
  rankup:
    description: Abre el menú de RankUp
    aliases: [rango, ranks, rankup]
    permission: fresh.admin
  tempfly:
    description: Otorga fly temporal a un jugador.
    permission: fresh.admin.tempfly
    permission-message: §cNo tienes permiso.
  battlepass:
    description: Abre el Pase de Batalla.
    aliases: [pase, bp]
    permission: fresh.battlepass
permissions:
  fresh.admin:
    description: Permite recargar los módulos del plugin
    default: op
  fresh.player:
    description: Permisos básicos para jugadores.
    default: true