# ====================================================================================================
#                                 ETHERIUM - RANKUP CONFIG
# ====================================================================================================
settings:
  enabled: false
  # Prefijo visual por defecto para un usuario que no tiene ningún rango comprado (Nivel 0)
  default_rank_prefix: "&8[&7Sin Rango&8]"